apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-oas-4715
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/h4rkon/argotest.git
    targetRevision: develop
    path: helm/argotest-environment
    helm:
      valueFiles:
        - ../../environments/feature-oas-4715/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-oas-4715
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
