apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  namespace: develop
  labels:
    app: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
        - name: serviceb
          image: ghcr.io/h4rkon/serviceb:develop-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
