apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: feature-branches
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - github:
        owner: h4rkon
        repo: argotest
        tokenRef:
          secretName: github-token
          key: token
        filters:
          - branchMatch: '^feature/.*$'
  template:
    metadata:
      name: '{{ .branchNormalized }}-services'
    spec:
      project: default
      source:
        repoURL: https://github.com/h4rkon/argotest.git
        targetRevision: '{{ .branch }}'
        path: kubernetes/feature
        kustomize:
          images:
            - name: ghcr.io/h4rkon/servicea
              newTag: '{{ regexFind "[A-Z]+-[0-9]+" .branch }}-latest'
            - name: ghcr.io/h4rkon/serviceb
              newTag: '{{ regexFind "[A-Z]+-[0-9]+" .branch }}-latest'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .branchNormalized }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
