namespace: feature-oas-4715
services:
  servicea:
    enabled: true
    image:
      repository: ghcr.io/h4rkon/servicea
      tag: develop-latest
    service:
      port: 80
      targetPort: 3000
    ingress:
      enabled: true
      className: nginx
      host: servicea-feature-oas-4715.192.168.5.1.sslip.io
  serviceb:
    enabled: true
    image:
      repository: ghcr.io/h4rkon/serviceb
      tag: develop-latest
    service:
      port: 80
      targetPort: 3000
    ingress:
      enabled: true
      className: nginx
      host: serviceb-feature-oas-4715.192.168.5.1.sslip.io
